INSERT INTO produse (denumire, categorie, pret, ingrediente, este_picant, este_vegetarian, este_disponibil) VALUES
('Apă plată', 'Băuturi nespirtoase', 8.0, 'Apă', false, true, true),
('Apă minerală', 'Băuturi nespirtoase', 9.0, 'Apă mineralizată', false, true, true),
('Limonadă', 'Băuturi nespirtoase', 15.0, 'Lămâie, apă, zahăr, mentă', false, true, true),
('Bruschete cu roșii', 'Aperitive', 20.0, 'Pâine prăjită, roșii, usturoi, ulei de măsline', false, true, true),
('Pesto', 'Aperitive', 22.0, 'Pâine prăjită, busuioc, parmezan, muguri de pin, ulei de măsline', false, true, true),
('Bruschete cu somon', 'Aperitive', 30.0, 'Pâine prăjită, somon afumat, cremă de brânză', false, false, true),
('Supă cremă de roșii', 'Aperitive', 24.0, 'Roșii pasate, busuioc, smântână lichidă, crutoane', false, true, true),
('Platou Brânzeturi', 'Aperitive', 55.0, 'Brie, gorgonzola, parmezan, nuci, struguri, miere', false, true, true),
('Hummus cu muguri de pin', 'Aperitive', 26.0, 'Năut, tahini, lămâie, ulei de măsline, lipie', false, true, true),
('Salată Caprese', 'Aperitive', 28.0, 'Mozzarella di bufala, roșii, sos pesto, busuioc proaspăt', false, true, true),
('Creveți în sos de vin', 'Aperitive', 48.0, 'Creveți, usturoi, unt, vin alb, pătrunjel, ardei iute', true, false, true),
('Camembert la cuptor', 'Aperitive', 34.0, 'Brânză camembert, cimbru, usturoi, dulceață de afine, pâine', false, true, true),
('Salată Caesar', 'Aperitive', 36.0, 'Salată romană, piept de pui la grătar, crutoane, parmezan, sos Caesar', false, false, true),
('Șnițel de pui cu cartofi', 'Feluri principale', 39.0, 'Piept de pui, pesmet panko, cartofi prăjiți, sos de usturoi', false, false, true),
('T someon la grătar', 'Feluri principale', 58.0, 'File de somon, legume la grătar, sos de lămâie cu unt', false, false, true),
('Paste Quattro Formaggi', 'Feluri principale', 42.0, 'Paste, gorgonzola, parmezan, fontina, mozzarella, smântână', false, true, true),
('Coaste de porc BBQ', 'Feluri principale', 62.0, 'Coaste de porc la cuptor, sos barbeque, cartofi wedges', false, false, true),
('Tagliata de vită', 'Feluri principale', 85.0, 'Vrăbioară de vită, rucola, roșii cherry, fulgi de parmezan', false, false, true),
('Pizza Quattro Stagioni', 'Feluri principale', 44.0, 'Aluat pizza, sos roșii, mozzarella, șuncă, ciuperci, măsline, anghinare', false, false, true),
('Pui Mexican', 'Feluri principale', 41.0, 'Piept de pui, ardei gras, porumb, fasole roșie, sos iute, orez', true, false, true),
('Paste cu fructe de mare', 'Feluri principale', 49.0, 'Spaghete, creveți, midii, calamar, sos de roșii, usturoi', false, false, true),
('Burger Vegetarian', 'Feluri principale', 43.0, 'Chiflă, chiftea din năut și mazăre, cheddar, castraveți murați, cartofi', false, true, true),
('Pulpă de rață confiată', 'Feluri principale', 68.0, 'Pulpă de rață, piure de cartofi cu trufe, sos de fructe de pădure', false, false, true),
('Cuba Libre', 'Băuturi spirtoase', 24.0, 'Rom, Coca-Cola, suc de lime, gheață', false, true, true),
('Mojito', 'Băuturi spirtoase', 26.0, 'Rom alb, mentă proaspătă, lime, zahăr brun, apă minerală', false, true, true),
('Aperol Spritz', 'Băuturi spirtoase', 28.0, 'Aperol, Prosecco, apă minerală, felie de portocală', false, true, true),
('Negroni', 'Băuturi spirtoase', 30.0, 'Gin, Campari, Vermut roșu, coajă de portocală', false, true, true),
('Vodka Cranberry', 'Băuturi spirtoase', 22.0, 'Vodka, suc de merișoare, gheață', false, true, true),
('Shot Jägermeister', 'Băuturi spirtoase', 12.0, 'Lichior de ierburi Jägermeister', false, true, true),
('Old Fashioned', 'Băuturi spirtoase', 32.0, 'Bourbon, bitter, zahăr, coajă de portocală', false, true, true),
('Coca-Cola', 'Băuturi nespirtoase', 10.0, 'Băutură răcoritoare cărbogazoasă', false, true, true),
('Fanta de portocale', 'Băuturi nespirtoase', 10.0, 'Băutură răcoritoare cărbogazoasă cu gust de portocale', false, true, true),
('Sprite', 'Băuturi nespirtoase', 10.0, 'Băutură răcoritoare cărbogazoasă cu gust de lămâie', false, true, true),
('Ice Tea cu piersici', 'Băuturi nespirtoase', 12.0, 'Ceai negru rece cu aromă de piersică', false, true, true),
('Espresso', 'Băuturi nespirtoase', 9.0, 'Cafea espresso simplă', false, true, true),
('Cappuccino', 'Băuturi nespirtoase', 14.0, 'Espresso, lapte cald, spumă de lapte', false, true, true),
('Limonadă cu căpșuni', 'Băuturi nespirtoase', 17.0, 'Lămâie, piure de căpșuni, apă, zahăr, gheață', false, true, true);

INSERT INTO utilizatori (email, username, password, role) VALUES
('admin@restaurant.null', 'ADMIN', 'adminRestaurantMagic12', 'ADMIN'),
('ospatar@restaurant.null', 'ospatar', '1234', 'OSPATAR');

